// Generated by gencpp from file AutoCircle_generater/Sensor_DistanceRequest.msg
// DO NOT EDIT!


#ifndef AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCEREQUEST_H
#define AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace AutoCircle_generater
{
template <class ContainerAllocator>
struct Sensor_DistanceRequest_
{
  typedef Sensor_DistanceRequest_<ContainerAllocator> Type;

  Sensor_DistanceRequest_()
    : A(0)  {
    }
  Sensor_DistanceRequest_(const ContainerAllocator& _alloc)
    : A(0)  {
  (void)_alloc;
    }



   typedef int8_t _A_type;
  _A_type A;





  typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Sensor_DistanceRequest_

typedef ::AutoCircle_generater::Sensor_DistanceRequest_<std::allocator<void> > Sensor_DistanceRequest;

typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceRequest > Sensor_DistanceRequestPtr;
typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceRequest const> Sensor_DistanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace AutoCircle_generater

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'AutoCircle_generater': ['/home/haonan/catkin_ws/src/AutoCircle_generater/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97e33c7f5f1563457ad3097549b87ad9";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97e33c7f5f156345ULL;
  static const uint64_t static_value2 = 0x7ad3097549b87ad9ULL;
};

template<class ContainerAllocator>
struct DataType< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AutoCircle_generater/Sensor_DistanceRequest";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 A\n\
";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensor_DistanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::AutoCircle_generater::Sensor_DistanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int8_t>::stream(s, indent + "  ", v.A);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCEREQUEST_H
