// Generated by gencpp from file AutoCircle_generater/Sensor_Distance.msg
// DO NOT EDIT!


#ifndef AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCE_H
#define AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCE_H

#include <ros/service_traits.h>


#include <AutoCircle_generater/Sensor_DistanceRequest.h>
#include <AutoCircle_generater/Sensor_DistanceResponse.h>


namespace AutoCircle_generater
{

struct Sensor_Distance
{

typedef Sensor_DistanceRequest Request;
typedef Sensor_DistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sensor_Distance
} // namespace AutoCircle_generater


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::AutoCircle_generater::Sensor_Distance > {
  static const char* value()
  {
    return "abba9e8845d4167fcc89d179b71a127a";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_Distance&) { return value(); }
};

template<>
struct DataType< ::AutoCircle_generater::Sensor_Distance > {
  static const char* value()
  {
    return "AutoCircle_generater/Sensor_Distance";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_Distance&) { return value(); }
};


// service_traits::MD5Sum< ::AutoCircle_generater::Sensor_DistanceRequest> should match 
// service_traits::MD5Sum< ::AutoCircle_generater::Sensor_Distance > 
template<>
struct MD5Sum< ::AutoCircle_generater::Sensor_DistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::AutoCircle_generater::Sensor_Distance >::value();
  }
  static const char* value(const ::AutoCircle_generater::Sensor_DistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::AutoCircle_generater::Sensor_DistanceRequest> should match 
// service_traits::DataType< ::AutoCircle_generater::Sensor_Distance > 
template<>
struct DataType< ::AutoCircle_generater::Sensor_DistanceRequest>
{
  static const char* value()
  {
    return DataType< ::AutoCircle_generater::Sensor_Distance >::value();
  }
  static const char* value(const ::AutoCircle_generater::Sensor_DistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::AutoCircle_generater::Sensor_DistanceResponse> should match 
// service_traits::MD5Sum< ::AutoCircle_generater::Sensor_Distance > 
template<>
struct MD5Sum< ::AutoCircle_generater::Sensor_DistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::AutoCircle_generater::Sensor_Distance >::value();
  }
  static const char* value(const ::AutoCircle_generater::Sensor_DistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::AutoCircle_generater::Sensor_DistanceResponse> should match 
// service_traits::DataType< ::AutoCircle_generater::Sensor_Distance > 
template<>
struct DataType< ::AutoCircle_generater::Sensor_DistanceResponse>
{
  static const char* value()
  {
    return DataType< ::AutoCircle_generater::Sensor_Distance >::value();
  }
  static const char* value(const ::AutoCircle_generater::Sensor_DistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCE_H
