// Generated by gencpp from file AutoCircle_generater/Sensor_DistanceResponse.msg
// DO NOT EDIT!


#ifndef AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCERESPONSE_H
#define AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace AutoCircle_generater
{
template <class ContainerAllocator>
struct Sensor_DistanceResponse_
{
  typedef Sensor_DistanceResponse_<ContainerAllocator> Type;

  Sensor_DistanceResponse_()
    : distance(0.0)  {
    }
  Sensor_DistanceResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Sensor_DistanceResponse_

typedef ::AutoCircle_generater::Sensor_DistanceResponse_<std::allocator<void> > Sensor_DistanceResponse;

typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceResponse > Sensor_DistanceResponsePtr;
typedef boost::shared_ptr< ::AutoCircle_generater::Sensor_DistanceResponse const> Sensor_DistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace AutoCircle_generater

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'AutoCircle_generater': ['/home/haonan/catkin_ws/src/AutoCircle_generater/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AutoCircle_generater/Sensor_DistanceResponse";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n\
\n\
";
  }

  static const char* value(const ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensor_DistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::AutoCircle_generater::Sensor_DistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOCIRCLE_GENERATER_MESSAGE_SENSOR_DISTANCERESPONSE_H
